### PR TITLE
Rename module to machine-api-provider-azure

### PR DESCRIPTION
**Pull request by alexander-demichev**
Rename module to machine-api-provider-azure, this repository is not a fork of https://github.com/kubernetes-sigs/cluster-api-provider-azure

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/approve

Does the CI need to be updated? It has a repo path with it right?

**Comment by alexander-demichev** [comment]
@JoelSpeed Yes, https://github.com/openshift/ocp-build-data/blob/openshift-4.10/images/ose-azure-machine-controllers.yml#L6 we should merge this now so we can update both module name and repo at the same time.

**Comment by JoelSpeed** [comment]
@alexander-demichev Is there anything within the release repo that needs updating as well? Or is that all straight forward?

**Comment by alexander-demichev** [comment]
This image yaml should be all and I believe the ART team will do it for us if I open a ticket.

**Pull request merged**
