### PR TITLE
OCPCLOUD-2192: Bump k8s packages to v1.28

### PR DESCRIPTION
**Pull request by odvarkadaniel**
Bump k8s dependencies to 1.28

### CODE REVIEW

**Comment by JoelSpeed** [comment]
We need to see that this doesn't break single zone CPMS before we can merge this, once the units are fixed, we can run an aggregate job

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by odvarkadaniel** [comment]
Should be ready to review - CI is green, aggregation job also passed, @JoelSpeed

**Comment by JoelSpeed** [comment]
Can see a green westus cluster in the aggregation results, so I'm happy that the previous issue is fixed
/approve
/lgtm

**Pull request merged**
