### PR TITLE
CORS-2517: migrate from ADAL to azidentity

### PR DESCRIPTION
**Pull request by r4f4**
ADAL is being deprecated, so use the new authentication library azidentity with an adapter so it works with old SDK clients.

### CODE REVIEW

**Comment by r4f4** [comment]
/hold
while I try to understand what's different about the e2e-azure-operator job.

**Comment by elmiko** [comment]
that error does look odd, perhaps it is just a flake.

**Comment by JoelSpeed** [comment]
Had a quick scan through the logs and the machine controller appears to be working relatively ok, lets try those tests again
/retest-required

**Comment by JoelSpeed** [comment]
/retest-required

A single cluster autoscaler test failed, I think we are probably OK to skip as I don't think this PR is causing that, but will try once more

**Comment by r4f4** [comment]
Rebased to fix merge conflicts.

**Comment by JoelSpeed** [comment]
The test failed this time on an autoscaler test, which we have been seeing sporadically across the board, I don't think it's related to the changes here

@elmiko @RadekManak did you have any additional feedback or are you happy to LGTM this?

/retest-required

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
@r4f4 Do we still need a hold on this?

**Comment by r4f4** [comment]
Ops, no we don't.
/hold cancel

**Comment by r4f4** [comment]
Rebased to fix merge conflicts.

**Comment by r4f4** [comment]
@elmiko if this looks good, you'll need to stamp it again. Tks.

**Pull request merged**
