### PR TITLE
Revert "Merge pull request #72 from RadekManak/azure-zone-no-pointer"

### PR DESCRIPTION
**Pull request by neisw**
This reverts commit 761536e0b365dc1a24f7123db73c777b7db38841, reversing changes made to 458e10c9b4f57f1c26613da7e0c2b5feb7118921.

TRT is observing failures in payloads like [4.14.0-0.nightly-2023-08-25-105956](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-08-25-105956)  where master nodes are deleted during azure upgrades [periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade/1695029023366713344)

We have opened [TRT-1208](https://issues.redhat.com/browse/TRT-1208) to track the issue and identified https://github.com/openshift/machine-api-provider-azure/pull/72/ with help from @JoelSpeed 

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are opening this revert to attempt to get payloads back to a functional state.

Running the payload-aggregate command to verify
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run pperiodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade jobs on the unrevert.  It is believed that this issue is due to multiple repos needing to be updated at the same time so how the fix gets validated will need to be reviewed.

### CODE REVIEW

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by RadekManak** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

None got scheduled in impacted westus zone.

**Comment by RadekManak** [comment]
We believe that this PR is the one causing the failure. Hope that the next aggregate lands on westus to confirm.
/hold cancel

The tests passed both before the PR we are reverting and when merging the PR we are reverting. There have been no other PRs since. There must be something else that changed that is causing the jobs to fail. 
/override ci/prow/govet
/override ci/prow/goimports

**Pull request merged**
