### PR TITLE
OCPBUGS-1411: Bump k8s dependencies to 1.25

### PR DESCRIPTION
**Pull request by lobziik**
also update azure sdk, controller-runtime and openshift/api

### CODE REVIEW

**Comment by elmiko** [comment]
looks like something broke the unit/vet tests. possibly something missing in the vendor? (looks like compile failure)

**Comment by lobziik** [comment]
@elmiko need merge this first: https://github.com/openshift/machine-api-provider-azure/pull/28 ...

**Comment by lobziik** [comment]
Have feeling that it did use go 1.17

**Comment by lobziik** [comment]
https://github.com/openshift/release/pull/32619 this need to go first

**Review by elmiko — COMMENTED** [review]
looking better now
/approve
/lgtm

**Comment by lobziik** [comment]
Added commit with golang image update from this pr https://github.com/openshift/machine-api-provider-azure/pull/28

Fixed goimports with follow-up commit

**Comment by JoelSpeed** [comment]
Webhook failures are fixed by openshift/machine-api-operator#1076, otherwise tests look good. Happy for this to merge
/override ci/prow/e2e-azure-operator

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-azure-operator

Known issue with the autoscaler tests right now which is being worked on, else this passed, happy this should merge

**Pull request merged**
