### PR TITLE
Enable configuration of boot diagnostics when creating VMs

### PR DESCRIPTION
**Pull request by JoelSpeed**
We are seeing a large number of Azure VM failures in CI. It would be good to be able to understand what is breaking on those VMs, but without the serial log configured, we cannot see what is happening to cause the VMs to fail to boot.

This PR adds options to the Machine provider spec to allow the user to choose from either an Azure provisioned or customer provisioned storage account, which then enables the boot diagnostics for the VM.

This should allow us to configure boot diagnostics and fetch the full serial logs for failing VMs.

Note, upstream enable azure managed boot diagnostics by default (ie no way to turn this off). There is a cost implication of $0.05/GB/Month for the storage. Each VM is capped at 1GB of data. 

We may want to follow the upstream pattern and just always enable boot diagnostics to make any transitions smoother, though this obviously has cost implications for customers.

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Review by damdo — COMMENTED** [review]
LGTM
Do you think it's worth adding a test to check the diagnostic config validation behaviour?

**Review by elmiko — COMMENTED** [review]
lgtm, i agree with @damdo though, adding a simple unit test for the `createDiagnosticsConfig` seems like a good thing (assuming it's not a royal pain to mock the provider spec).

**Review by damdo — COMMENTED** [review]
Thanks!
/lgtm

**Pull request merged**
